modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
[[mods]]
modId="honeystickypistonmod"
version="${file.jarVersion}"
displayName="Honey Sticky Piston Mod"
logoFile="examplemod.png"
credits="Thanks to Cy4 and their community for teaching me how to mod, samjviana for a helpful reference, and Firestorm2173 for the idea!"
authors="MWR_"
description='''
A new sticky piston that you can craft with honey!
'''
[[dependencies.honeystickypistonmod]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.honeystickypistonmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"