modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
[[mods]]
modId="honeystickypistonmod"
version="${file.jarVersion}"
displayName="Honey Sticky Piston Mod"
logoFile="examplemod.png"
credits="Thanks to Cy4 and their community for teaching me how to mod and samjviana for a helpful reference!"
authors="MWR_"
description='''
A new sticky piston that you can craft with honey!
'''
[[dependencies.myfirstmod]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.myfirstmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"